spring:
    config:
        activate:
            on-profile: dev
    devtools:
        add-properties: true
    datasource:
        url: jdbc:postgresql://localhost:5432/efyp
        username: postgres
        password: 5zm7aa8o
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        hibernate:
            ddl-auto: update
    mail:
        host: smtp.gmail.com
        port: 587
        username: bangtranvan08@gmail.com
        password: inztsmgbywgzmevn
redis:
  port: 6379
  host: localhost
  password: 5zm7aa8o


environment:
    info: develop_environment

# application-dev.yml
springdoc:
    api-docs:
        enabled: true
    swagger-ui:
        enabled: true
openapi:
    service:
        api-docs: e-fyp
        server: http://localhost:${server.port}
        title: E-FYP API
        version: 1.0.0